development:
  rate_api:
    host: "http://localhost:8080/pricing"
    token: "04aa6f42aa03f220c2ae9a276cd68c62"
  retry:
    count: 3
    backoff: 1 #minutes
  batch_interval: 1 #minutes

test:
  rate_api:
    host: "http://localhost:8080/pricing"
    token: "04aa6f42aa03f220c2ae9a276cd68c62"
  retry:
    count: 1
    backoff: 0
  batch_interval: 5

production:
  rate_api:
    host: "http://localhost:8080/pricing"
    token: "04aa6f42aa03f220c2ae9a276cd68c62"
  retry:
    count: 3
    backoff: 1
  batch_interval: 5
